User.create!(name: 'Anthony', password: 'password', age: Faker::Number.between(20,50).to_s,email: 'user1@example.com',phone: '1111111111', address: 'Los Angeles')
User.create!(name: 'Boris', password: 'password', age: Faker::Number.between(20,50).to_s,email: 'user2@example.com',phone: '0000000000', address: 'New York')
User.create!(name: 'Charles', password: 'password', age: Faker::Number.between(20,50).to_s,email: 'user3@example.com',phone: '9999999999', address: 'Moscow')
User.create!(name: 'Dan', password: 'password', age: Faker::Number.between(20,50).to_s,email: 'user4@example.com',phone: '1010101101', address: 'London')
User.create!(name: 'Erik', password: 'password', age: Faker::Number.between(20,50).to_s,email: 'user5@example.com',phone: '1111111111', address: 'Madrid')
User.create!(name: 'Farhan', password: 'password', age: Faker::Number.between(20,50).to_s,email: 'user6@example.com',phone: '1213141515', address: 'Bengaluru')
User.create!(name: 'Gurdeep', password: 'password', age: Faker::Number.between(20,50).to_s,email: 'user7@example.com',phone: '1234121313', address: 'New Delhi')
